#!/bin/bash

buck-out/gen/scripts/njormrod/hanabi/hanabi \
  --record_score 24 \
  --noalways_brute_force \
  --noallow_magic \
  "$@" 2>/tmp/hanabi_logs
exit 0

# --hands_file /data/users/njormrod/hanabi_hands.v2.bin \
# --seed_file /data/users/njormrod/hanabi_seeds.txt \
